import { useEffect, useState } from 'react'
export default function AdminProducts(){
  const [pwd,setPwd]=useState(''); const [auth,setAuth]=useState(false); const [products,setProducts]=useState([]); const [form,setForm]=useState({ title:'', slug:'', description:'', price:'', stock:0, image:'', sku:''})
  useEffect(()=>{ if(auth) load() },[auth])
  async function load(){ const res = await fetch('/api/admin/products',{ headers: { 'x-admin-password': pwd } }); if(res.status===200) setProducts(await res.json()); else alert('Auth fehlgeschlagen') }
  function login(e){ e.preventDefault(); setAuth(true) }
  async function createProduct(e){ e.preventDefault(); const body = { title: form.title, slug: form.slug || form.title.toLowerCase().replace(/\s+/g,'-'), description: form.description, priceCents: Math.round(parseFloat(form.price||0)*100), currency: 'EUR', image: form.image, sku: form.sku, stock: Number(form.stock||0) }; const res = await fetch('/api/admin/products',{ method:'POST', headers:{ 'Content-Type':'application/json','x-admin-password':pwd }, body: JSON.stringify(body) }); if(res.status===201){ setForm({ title:'', slug:'', description:'', price:'', stock:0, image:'', sku:'' }); load() } else alert('Fehler beim Erstellen') }
  async function del(id){ if(!confirm('Produkt löschen?')) return; await fetch('/api/admin/products?id='+id,{ method:'DELETE', headers:{ 'x-admin-password': pwd } }); load() }
  return (
    <div className="container">
      {!auth && (<form onSubmit={login} className="max-w-md"><h2 className="text-xl font-bold mb-2">Admin Login</h2><input type="password" className="border p-2 w-full" placeholder="Admin Passwort" value={pwd} onChange={e=>setPwd(e.target.value)} /><button className="mt-2 px-3 py-2 bg-gray-800 text-white rounded">Login</button></form>)}
      {auth && (<div><h1 className="text-2xl font-bold mb-4">Produkte verwalten</h1><form onSubmit={createProduct} className="mb-6 border p-4"><input className="w-full border p-2 mb-2" placeholder="Titel" value={form.title} onChange={e=>setForm({...form, title: e.target.value})} /><input className="w-full border p-2 mb-2" placeholder="Slug" value={form.slug} onChange={e=>setForm({...form, slug: e.target.value})} /><input className="w-full border p-2 mb-2" placeholder="Bild URL" value={form.image} onChange={e=>setForm({...form, image: e.target.value})} /><input className="w-full border p-2 mb-2" placeholder="SKU" value={form.sku} onChange={e=>setForm({...form, sku: e.target.value})} /><input className="w-full border p-2 mb-2" placeholder="Preis (EUR)" value={form.price} onChange={e=>setForm({...form, price: e.target.value})} /><input className="w-full border p-2 mb-2" placeholder="Bestand" value={form.stock} onChange={e=>setForm({...form, stock: e.target.value})} /><textarea className="w-full border p-2 mb-2" placeholder="Beschreibung" value={form.description} onChange={e=>setForm({...form, description: e.target.value})} /><button className="px-3 py-2 bg-green-600 text-white rounded">Produkt erstellen</button></form><div><h2 className="text-xl font-semibold mb-2">Produkte</h2>{products.map(p => (<div key={p.id} className="border p-3 mb-2 flex justify-between items-center"><div><div className="font-semibold">{p.title} ({p.sku||'-'})</div><div className="text-sm">{(p.priceCents/100).toFixed(2)} {p.currency} — Bestand: {p.stock}</div></div><div className="flex gap-2"><a className="px-2 py-1 bg-blue-600 text-white rounded" href={`/product/${p.id}`} target="_blank">ansicht</a><button onClick={()=>del(p.id)} className="px-2 py-1 bg-red-600 text-white rounded">löschen</button></div></div>))}</div></div>)}
    </div>
  )
}
